# Generated by Django 5.1.7 on 2025-03-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.classes', verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
